spring:
  application:
    name: ors-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/db_swimdom}
    username: ${DB_USERNAME:swimdom_admin}
    password: ${DB_PASSWORD:swimdom_pwd}
  jpa:
    properties:
      hibernate:
        globally_quoted_identifiers=true

  liquibase:
    change-log: db/changelog/changelog-master.yml
    enabled: true
    default-schema: public
    drop-first: false
logging:
    level:
      root: INFO
management:
  endpoints:
    enabled-by-default: false
    web.exposure.include: health, prometheus, loggers
  endpoint:
    health.enabled: true
    prometheus.enabled: true
    loggers.enabled: true
token:
    secret: JwtTokenSecret
    prefix: "Bearer"
    expiration_time: 600_000
    content_type: application/json
    header_string: "Authorization"
