server:
  port: ${POOL_SERVICE_PORT:8083}
spring:
  application:
    name: poolservice
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      group-id: poolservice
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
topics:
  pool-events: ${POOL_EVENTS_TOPIC:pool.events}
  user-events: ${USER_EVENTS_TOPIC:user.events}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5434/swimdom_pool}
    username: ${DB_USERNAME:swimdom_admin}
    password: ${DB_PASSWORD:swimdom_pwd}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true
    default-schema: public
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: false
management:
  endpoints:
    web:
      exposure:
        include: health,info


