services:
  postgres:
    image: "postgres:17.5"
    environment:
      POSTGRES_DB: "db_swimdom"
      POSTGRES_USER: "swimdom_admin"
      POSTGRES_PASSWORD: "swimdom_pwd"
    ports:
      - "5432:5432"
    restart: 'always'
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ors-service -d db_swimdom'" ]

#   ors-service:
#     build:
#       dockerfile: ./Dockerfile
#     ports:
#       - 8080:8080
#     environment:
#       - 'DB_URL=jdbc:postgresql://postgres/db_swimdom'
#       - 'DB_USERNAME=swimdom_admin'
#       - 'DB_PASSWORD=swimdom_pwd'
#     depends_on:
#       postgres:
#         condition: service_healthy