plugins {
    id 'java'
    id 'io.spring.dependency-management'
}

group = parent.group
version = parent.version

dependencies {
    implementation project(":adapter")
    testImplementation 'com.github.tomakehurst:wiremock-standalone:3.0.1'
    testImplementation 'it.ozimov:embedded-redis:0.7.2'
    implementation 'net.logstash.logback:logstash-logback-encoder:7.4'
}

apply {
    plugin("org.springframework.boot")
}