databaseChangeLog:
  - include:
      file: db/changelog/changeset/3-create-pool.yaml
  - include:
      file: db/changelog/changeset/4-create-pool-working-hour.yaml
  - include:
      file: db/changelog/changeset/5-create-subscription.yaml
  - include:
      file: db/changelog/changeset/6-create-user-subscription.yaml


