openapi: 3.0.3

info:
  title: Swimming Service
  description: Service for buying tickets at swimming pools.
  version: 1.0.0

tags:
  - name: Pools
    description: Operations related to swimming pools

paths:
  /api/v1/pools:
    $ref: './pool-dtos.yaml#/pools'
  /api/v1/subscriptions:
    $ref: './subscriptions-dtos.yaml#/subscriptions'
  /api/v1/subscriptions/{id}:
    $ref: './subscriptions-dtos.yaml#/subscriptionById'
  /api/v1/user-subscriptions:
    $ref: './subscriptions-dtos.yaml#/userSubscriptions'
  /api/v1/user-subscriptions/{id}:
    $ref: './subscriptions-dtos.yaml#/userSubscriptionById'


