openapi: 3.0.3

info:
  title: Swimming Service
  description: Service for buying tickets at swimming pools.
  version: 1.0.0

tags:
  - name: Pools
    description: Operations related to swimming pools

paths:
  /api/v1/pools:
    post:
      tags:
        - Pools
      summary: Create a new pool
      description: Adds a new swimming pool to the system.
      operationId: createPool
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoolDto'
      responses:
        '201':
          description: Pool created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'

    get:
      tags:
        - Pools
      summary: Retrieve all available pools
      description: Returns a list of all swimming pools available for ticket purchase.
      operationId: getPools
      responses:
        '200':
          description: A list of pools
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PoolDto'
        '204':
          description: No pools found
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '409':
          $ref: '#/components/responses/Conflict'
        '500':
          $ref: '#/components/responses/InternalServerError'


components:
  schemas:
    PoolDto:
      $ref: './pool-dtos.yaml#/components/schemas/PoolDto'
    ErrorDto:
      $ref: './error-dto.yaml#/components/schemas/ErrorDto'
    PoolWorkingHoursDto:
      $ref: './pool-dtos.yaml#/components/schemas/PoolWorkingHoursDto'

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    NotFound:
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorDto'
