<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.innowise.swimdom</groupId>
        <artifactId>userservice</artifactId>
        <version>${revision}</version>
    </parent>
    <artifactId>adapter</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc.openapi.version}</version>
        </dependency>
        <dependency>
            <groupId>com.innowise.swimdom</groupId>
            <artifactId>dto</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.innowise.swimdom</groupId>
            <artifactId>service-api</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.innowise.swimdom</groupId>
            <artifactId>domain</artifactId>
            <version>${revision}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>


